name: Daily User Commit Check

on:
  schedule:
    - cron: '00 18 * * *' # Runs at 02:00 UTC daily
  push:
    branches: ["main"]

jobs:
  check-user-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # to ensure access to the send_mail_if_no_commit
        uses: actions/checkout@v3

      - name: Install mailutils
        run: sudo apt-get update && sudo apt-get install -y mailutils

      - name: Set script permissions
        run: chmod +x ./send_mail_if_no_commit.sh

      - name: Check for user activity
        id: user-activity
        env:
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
          GITHUB_USER: jeromevde
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
        run: |
          ./send_mail_if_no_commit.sh
