name: Send Email on Commit

on:
  push:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
        run: |
          # Enable verbose logging for curl
          set -x
          # Export environment variables if needed
          export EMAIL_USER="$EMAIL_USER"
          export GMAIL_TOKEN="$GMAIL_TOKEN"

          # Execute curl command with verbose output
          curl --verbose \
            --url 'smtps://smtp.gmail.com:465' \
            --ssl-reqd \
            --mail-from "$EMAIL_USER" \
            --mail-rcpt "$EMAIL_USER" \
            --upload-file <(echo -e "Subject: test test") \
            --user "$EMAIL_USER:$GMAIL_TOKEN"